{
   "no_index" : {
      "directory" : [
         "t",
         "inc"
      ]
   },
   "meta-spec" : {
      "version" : 1.4,
      "url" : "http://module-build.sourceforge.net/META-spec-v1.4.html"
   },
   "generated_by" : "ExtUtils::MakeMaker version 6.54",
   "distribution_type" : "module",
   "version" : "2.10",
   "name" : "Deliantra-Client",
   "author" : [],
   "license" : "unknown",
   "build_requires" : {
      "ExtUtils::MakeMaker" : 0
   },
   "requires" : {
      "Deliantra" : 1.23,
      "BDB" : 1.83,
      "AnyEvent" : 4.331,
      "Pod::POM" : 0.15,
      "Compress::LZF" : 3.41,
      "Guard" : 1,
      "JSON::XS" : 2.2222,
      "Time::HiRes" : 0,
      "EV" : 3.42,
      "LWP" : 0
   },
   "abstract" : null,
   "configure_requires" : {
      "ExtUtils::MakeMaker" : 0
   }
}
