--- #YAML:1.0
name:               Deliantra-Client
version:            2.04
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent:       4.331
    BDB:            1.83
    Compress::LZF:  3.41
    Deliantra:      1.23
    EV:             3.42
    Guard:          1
    JSON::XS:       2.2222
    LWP:            0
    Pod::POM:       0.15
    Time::HiRes:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
